version: '3.8'

services:
  audio-to-text-service:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - MAX_CONTENT_LENGTH=100000000  # 100MB
    volumes:
      - ./templates:/app/templates
      - ./audio_to_text_service.py:/app/audio_to_text_service.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
